# Write your MySQL query statement below
# SELECT PRODUCT_ID FROM PRODUCTS
# WHERE LOW_FATS LIKE 'Y%' AND RECYCLABLE LIKE 'Y%';

SELECT PRODUCT_ID FROM PRODUCTS
WHERE LOW_FATS = 'Y' AND RECYCLABLE = 'Y';